trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputFolder: 'D:\Deploy\CalculatorApp'

steps:

# Checkout code
- checkout: self

# Install .NET
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore
- script: dotnet restore
  displayName: 'Restore'

# Build
- script: dotnet build .
  displayName: 'Build'

# Run Unit Tests
- script: dotnet test --configuration $(buildConfiguration) --no-build --logger "trx"
  displayName: 'Run Unit Tests'

# Publish Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/*.trx'

# Publish App
- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

# Deploy (Copy to Folder)
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'
    TargetFolder: '$(outputFolder)'
    OverWrite: true